# Generated by Django 4.2.7 on 2025-07-09 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_alter_signosvitales_frecuencia_cardiaca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriapadecimiento',
            name='padecimiento',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento_farmacologico_recetado',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tratamiento farmacológico recetado'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento_no_farmacologico',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Tratamiento no farmacológico'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='(5[0-9]|[6-9][0-9]|1[0-9]{2}|2[0-9]{2})')], verbose_name='Frecuencia cardíaca (ppm)'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.RegexValidator(regex='(3[0-9]|4[0-3]|5[0-9])(\\.[0-9])?')], verbose_name='Temperatura (°C)'),
        ),
    ]
