# Generated by Django 4.2.7 on 2025-10-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_categoriapadecimiento_padecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='imc',
            field=models.FloatField(blank=True, null=True, verbose_name='Índice de Masa Corporal(IMC)'),
        ),
    ]
