# Generated by Django 4.2.7 on 2025-10-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_remove_signosvitales_imc'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='imc',
            field=models.FloatField(blank=True, null=True, verbose_name='Índice de Masa Corporal(IMC)'),
        ),
    ]
