# Generated by Django 4.1.13 on 2024-11-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='medico',
            name='apellido_materno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medico',
            name='apellido_paterno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medico',
            name='contrasena',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medico',
            name='matricula',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido_paterno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contrasena',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='matricula',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
