# Generated by Django 4.1.13 on 2024-12-06 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener al menos 8 caracteres.', regex='^.{8,}$')], verbose_name='Contraseña'),
        ),
    ]
