# Generated by Django 4.1.13 on 2024-11-09 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id_historial', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, verbose_name='Id Historial')),
                ('enfermedades_cronicas', models.CharField(blank=True, max_length=150, null=True, verbose_name='Enfermedades crónicas')),
                ('alergias', models.CharField(blank=True, max_length=150, null=True, verbose_name='Alergias')),
                ('medicamento_usado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Medicamento usado')),
                ('esEmbarazada', models.BooleanField(default=False)),
                ('usaDrogas', models.BooleanField(default=False)),
                ('usaCigarro', models.BooleanField(default=False)),
                ('ingiereAlcohol', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.historialmedico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
