# Generated by Django 4.2.7 on 2025-02-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='usa_lentes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='usa_metodos_anticonceptivo',
            field=models.BooleanField(default=False, verbose_name='Usa métodos anticonceptivo'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='vida_sexual_activa',
            field=models.BooleanField(default=False),
        ),
    ]
