# Generated by Django 4.1.13 on 2024-12-02 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[A-ZÑÁÉÍÓÚ][a-zñáéíóú]+')], verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-ZÑÁÉÍÓÚ][a-zñáéíóú]+')], verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de clave no valido', regex='((ib|im|ii|ie|lsc|lg|am)[0-9][0-9][0-9][0-9][0-9][0-9])|([0-9][0-9][0-9][0-9][0-9][0-9])|(admin)[0-9]')], verbose_name='clave'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de correo no valido', regex='((ib|im|ii|ie|lsc|lg|am)[0-9][0-9][0-9][0-9][0-9][0-9])|([0-9][0-9][0-9][0-9][0-9][0-9])@itsatlixco\\.edu\\.mx|admin[0-9]@admin.com')], verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^([A-ZÑÁÉÍÓÚ][a-zñáéíóú]+)( [A-ZÑÁÉÍÓÚ][a-zñáéíóú]+)?$')], verbose_name='Nombres'),
        ),
    ]
