# Generated by Django 4.2.7 on 2025-05-17 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_clave_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener al entre 8 y 15 caracteres, incluir una letra mayúscula, un número y un caracter especial.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*#?&ñ_])[A-Za-z\\d@$!%*#?&ñ_]{8,15}$')], verbose_name='Contraseña'),
        ),
    ]
