# Generated by Django 4.2.7 on 2025-02-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_historialmedico_usa_lentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='usa_metodos_anticonceptivo',
            field=models.BooleanField(default=False, verbose_name='Usa métodos anticonceptivos'),
        ),
    ]
