# Generated by Django 4.1.13 on 2024-11-09 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_historialmedico_paciente_medico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialmedico',
            old_name='esEmbarazada',
            new_name='es_embarazada',
        ),
        migrations.RenameField(
            model_name='historialmedico',
            old_name='ingiereAlcohol',
            new_name='ingiere_alcohol',
        ),
        migrations.RenameField(
            model_name='historialmedico',
            old_name='usaCigarro',
            new_name='usa_cigarro',
        ),
        migrations.RenameField(
            model_name='historialmedico',
            old_name='usaDrogas',
            new_name='usa_drogas',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_administrador',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historial_medico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.historialmedico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
