# Generated by Django 4.1.13 on 2024-11-09 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_esembarazada_historialmedico_es_embarazada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialmedico',
            old_name='es_embarazada',
            new_name='esEmbarazada',
        ),
        migrations.RenameField(
            model_name='historialmedico',
            old_name='ingiere_alcohol',
            new_name='ingiereAlcohol',
        ),
        migrations.RenameField(
            model_name='historialmedico',
            old_name='usa_cigarro',
            new_name='usaCigarro',
        ),
        migrations.RenameField(
            model_name='historialmedico',
            old_name='usa_drogas',
            new_name='usaDrogas',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_staff',
            new_name='usuario_administrador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historial_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.historialmedico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
