# Generated by Django 4.1.13 on 2024-12-05 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_clave_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de clave no valido', regex='^((ib|im|ii|ie|lsc|lg|am)[0-9]{6})|(admin[0-9])|([0-9]{6})$')], verbose_name='clave'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de correo no valido', regex='^((ib|im|ii|ie|isc|lg|am)[0-9]{6}@itsatlixco\\.edu\\.mx)|(admin[0-9]@admin\\.com)|([0-9]{6}@itsatlixco\\.edu\\.mx)$')], verbose_name='Correo'),
        ),
    ]
