# Generated by Django 4.2.7 on 2025-02-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_historialmedico_usa_metodos_anticonceptivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialmedico',
            old_name='usa_metodos_anticonceptivo',
            new_name='usa_metodos_anticonceptivos',
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='id_historial',
            field=models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True, verbose_name='Id Historial'),
        ),
    ]
