# Generated by Django 4.2.7 on 2025-05-19 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='El apellido materno debe ser en mayúsculas', regex='^[A-ZÑÁÉÍÓÚ][A-ZÑÁÉÍÓÚ]+')], verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El apellido paterno debe ser en mayúsculas', regex='^[A-ZÑÁÉÍÓÚ][A-ZÑÁÉÍÓÚ]+')], verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre debe ser en mayúsculas y no contener números', regex='^([A-ZÑÁÉÍÓÚ][A-ZÑÁÉÍÓÚ]+)( [A-ZÑÁÉÍÓÚ][A-ZÑÁÉÍÓÚ]+)?$')], verbose_name='Nombres'),
        ),
    ]
