# Generated by Django 4.2.7 on 2025-08-03 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de clave no valido', regex='^((AM|BIE|BIS|BLG|CIE|CII|IB|IE|II|IM|ISC|LG|MI|MXI|MXM|MXS)[0-9]{4,6})|^(admin[0-9])|^([0-9]{4,6})$')], verbose_name='clave'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de correo no valido', regex='^(?:(?:(?:am|bie|bis|blg|cie|cii|ib|ie|ii|im|isc|lg|mi|mxi|mxm|mxs)\\d{6}|\\d{4,6}|[A-Za-z]+(?:\\.[A-Za-z]+))@itsatlixco\\.edu\\.mx|admin\\d@admin\\.com)$')], verbose_name='Correo'),
        ),
    ]
