# Generated by Django 4.2.7 on 2025-08-03 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_clave_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre debe ser en mayúsculas y no contener números', regex='^([A-ZÑÁÉÍÓÚ][A-ZÑÁÉÍÓÚ]+)( [A-ZÑÁÉÍÓÚ][A-ZÑÁÉÍÓÚ]+)?( [A-ZÑÁÉÍÓÚ][A-ZÑÁÉÍÓÚ]+)?$')], verbose_name='Nombres'),
        ),
    ]
