# Generated by Django 4.1.13 on 2024-11-11 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('padecimiento_actual', models.TextField()),
                ('tratamiento_no_farmacologico', models.TextField(blank=True, max_length=100, null=True, verbose_name='Tratamiento no farmacológico')),
                ('tratamiento_farmacologico_recetado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tratamiento farmacológico recetado')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Peso (kg)')),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Talla (m)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('frecuencia_cardíaca', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (bpm)')),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria (rpm)')),
                ('presion_arterial', models.CharField(blank=True, max_length=7, null=True, verbose_name='Presión arterial')),
                ('matricula_paciente', models.ForeignKey(limit_choices_to={'role': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_paciente', to=settings.AUTH_USER_MODEL)),
                ('paciente_medico', models.ForeignKey(limit_choices_to={'role': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
