# Generated by Django 4.1.13 on 2024-12-06 03:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('padecimiento_actual', models.TextField()),
                ('tratamiento_no_farmacologico', models.TextField(blank=True, max_length=100, null=True, verbose_name='Tratamiento no farmacológico')),
                ('tratamiento_farmacologico_recetado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tratamiento farmacológico recetado')),
                ('tipo_de_consulta', models.CharField(choices=[('M', 'Médica'), ('A', 'Asesoría')], default='M', max_length=1, verbose_name='Tipo de consulta')),
                ('clave_medico', models.ForeignKey(limit_choices_to={'role__nombre_rol': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_medico', to=settings.AUTH_USER_MODEL)),
                ('clave_paciente', models.ForeignKey(limit_choices_to={'role__nombre_rol': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_signos', models.BigAutoField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.RegexValidator(message='Formato de peso no valido', regex='([4-9][0-9]|1[0-9][0-9])\\.[0-9]')], verbose_name='Peso (kg)')),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.RegexValidator(message='Formato de talla no valido', regex='(1\\.[0-9][0-9]|2\\.[0-2][0-9])')], verbose_name='Talla (m)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.RegexValidator(message='Formato de temperatura no valido', regex='(3[5-9]|4[0-3])\\.[0-9]')], verbose_name='Temperatura (°C)')),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Formato de frecuencia cardíaca no valido', regex='(5[0-9]|[6-9][0-9]|100)')], verbose_name='Frecuencia cardíaca (bpm)')),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Formato de frecuencia cardíaca no valido', regex='^(12|1[3-9]|2[0-9]|3[0-9]|40)$')], verbose_name='Frecuencia respiratoria (rpm)')),
                ('presion_arterial', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Formato de presión arterial no valido', regex='\\b(1[01][0-9]|120|12[0-9]|1[3-9][0-9]|140)\\/(60|6[0-9]|70|7[0-9]|80|8[0-9]|90)\\b')], verbose_name='Presión arterial')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='consultas.consulta')),
            ],
        ),
    ]
