# Generated by Django 4.1.13 on 2024-11-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='paciente_medico',
            new_name='clave_medico',
        ),
    ]
