# Generated by Django 4.1.13 on 2025-02-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-fecha', '-id_consulta']},
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['-fecha', '-id_consulta'], name='consultas_c_fecha_66d5db_idx'),
        ),
    ]
