# Generated by Django 4.1.13 on 2024-11-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Talla (m)'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
    ]
