# Generated by Django 4.2.7 on 2025-04-23 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.RegexValidator(message='Formato de talla no valido (ej: "1.00-2.29")', regex='^(1\\.\\d{1,2}|2\\.[0-2]\\d?)')], verbose_name='Talla (m)'),
        ),
    ]
