# Generated by Django 4.1.13 on 2025-02-02 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_signosvitales_frecuencia_cardiaca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.RegexValidator(message='Formato de temperatura no valido (ej: "35.0-43.9")', regex='(3[5-9]|4[0-3])(\\.[0-9])?')], verbose_name='Temperatura (°C)'),
        ),
    ]
