# Generated by Django 4.1.13 on 2024-12-03 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_signosvitales_frecuencia_cardiaca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.RegexValidator(message='Formato de peso no valido', regex='([4-9][0-9]|1[0-9][0-9])\\.[0-9]')], verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.RegexValidator(message='Formato de temperatura no valido', regex='(3[5-9]|4[0-3])\\.[0-9]')], verbose_name='Temperatura (°C)'),
        ),
    ]
