# Generated by Django 4.2.7 on 2025-05-17 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_signosvitales_frecuencia_cardiaca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='(5[0-9]|[6-9][0-9]|100)')], verbose_name='Frecuencia cardíaca (ppm)'),
        ),
    ]
