# Generated by Django 4.1.13 on 2025-02-02 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_fecha_alter_signosvitales_temperatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
