# Generated by Django 4.2.7 on 2025-05-08 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de clave no valido', regex='^((ib|im|ii|ie|isc|lg|am)[0-9]{4,6})|^(admin[0-9])|^([0-9]{4,6})$')], verbose_name='clave'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de correo no valido', regex='^(?:(?:(?:ib|im|ii|ie|isc|lg|am)\\d{6}|\\d{4,6}|[A-Za-z]+(?:\\.[A-Za-z]+))@itsatlixco\\.edu\\.mx|admin\\d@admin\\.com)$')], verbose_name='Correo'),
        ),
    ]
