# Generated by Django 4.2.7 on 2025-10-31 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de clave no valido', regex='^((AM|BIE|BIS|BLG|BII|BIM|BIB|CLG|CIM|CIE|CII|CIB|IB|IE|II|IM|ISC|LG|MI|MXI|MXM|MXE|MXS|MIA)[0-9]{4,6})|^(admin[0-9])|^([0-9]{4,6})$')], verbose_name='clave'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de correo no valido', regex='^(?:(?:(?:am|bie|bis|blg|bii|bim|clg|cim|cie|cii|cib|ib|ie|ii|im|isc|lg|mi|mxi|mxm|mxe|mxs|mia)\\d{6}|\\d{4,6}|[A-Za-z]+(?:\\.[A-Za-z]+))@itsatlixco\\.edu\\.mx|admin\\d@admin\\.com)$')], verbose_name='Correo'),
        ),
    ]
