# Generated by Django 4.2.7 on 2025-10-31 19:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_clave_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre Completo')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Ingresa un teléfono válido.')], verbose_name='Teléfono')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddConstraint(
            model_name='contactoemergencia',
            constraint=models.UniqueConstraint(fields=('paciente', 'telefono'), name='unique_telefono_por_paciente'),
        ),
    ]
