# Generated by Django 4.2.7 on 2025-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='url_recurso',
            field=models.URLField(blank=True, null=True, verbose_name='URL del recurso'),
        ),
    ]
