# Generated by Django 4.2.7 on 2025-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_remove_publicacion_imagen_publicacion_url_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
